import 'package:sneakersapp/models/sneakers.dart';

List<Sneakers> dummySneakers = [
  Sneakers(
    name: "Jordan 1 Blue University",
    price: "420€",
    urlimage: "assets/JBU1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/JBU1.png"
          "assets/JBU2.png",
      "assets/JBU3.png",
      "assets/JBU4.png",
      "assets/JBU5.png",
      "assets/JBU6.png",
      "assets/JBU7.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Jordan 1 Hyper Royal",
    price: "480€",
    urlimage: "assets/JHR1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/JHR1.png",
      "assets/JHR2.png",
      "assets/JHR3.png",
      "assets/JHR4.png",
      "assets/JHR5.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Jordan 12 Red University",
    price: "500€",
    urlimage: "assets/J12RU1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/J12RU1.png",
      "assets/J12RU2.png",
      "assets/J12RU3.png",
      "assets/J12RU4.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Jordan 11 Jubilee 25th Anniversary",
    price: "299€",
    urlimage: "assets/J11JB1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/J11JB1.png",
      "assets/J11JB2.png",
      "assets/J11JB3.png",
      "assets/J11JB4.png",
      "assets/J11JB5.png",
      "assets/J11JB6.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Jordan 11 Adapt",
    price: "600€",
    urlimage: "assets/J11ADP1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/J11ADP1.png",
      "assets/J11ADP2.png",
      "assets/J11ADP3.png",
      "assets/J11ADP4.png",
      "assets/J11ADP5.png",
      "assets/J11ADP6.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Jordan 5 Raging Bull Red",
    price: "200€",
    urlimage: "assets/J5RC1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/J5RC1.png",
      "assets/J5RC2.png",
      "assets/J5RC3.png",
      "assets/J5RC4.png",
      "assets/J5RC5.png",
      "assets/J5RC6.png",
      "assets/J5RC7.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Jordan 4 Blue University",
    price: "380€",
    urlimage: "assets/J4BU1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/J4BU1.png",
      "assets/J4BU2.png",
      "assets/J4BU3.png",
      "assets/J4BU4.png",
      "assets/J4BU5.png",
      "assets/J4BU6.png",
      "assets/J4BU7.png",
      "assets/J4BU8.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
  Sneakers(
    name: "Nike Air Max 1 CLOT Kiss Of Death",
    price: "180€",
    urlimage: "assets/AMC1.png",
    description: "",
    category: "Sneakers",
    images: [
      "assets/AMC1.png",
      "assets/AMC2.png",
      "assets/AMC3.png",
      "assets/AMC4.png",
      "assets/AMC5.png",
      "assets/AMC6.png",
      "assets/AMC7.png",
      "assets/AMC8.png",
      "assets/AMC9.png",
      "assets/AMC10.png",
      "assets/AMC11.png",
      "assets/AMC12.png",
    ],
    size: ["10", "10.5", "11", "11.5", "12", "12.5", "13", "14", "15"],
  ),
];
